name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: nopcommerce:$(date +%Y%m%d%H%M%S)  # Define the tag as an environment variable

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kraigoavant/${{ env.IMAGE_TAG }}

    - name: Push Docker image to Docker Hub
      run: docker push kraigoavant/${{ env.IMAGE_TAG }}
