name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up image tag
      id: tag
      run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: kraigoavant  # Your Docker Hub username
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kraigoavant/nopcommerce:${{ env.IMAGE_TAG }}

    - name: Push Docker image to Docker Hub
      run: docker push kraigoavant/nopcommerce:${{ env.IMAGE_TAG }}
